# Generated by Django 5.0.4 on 2024-04-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_gender_onetimepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
