# Generated by Django 5.0.4 on 2024-05-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks_tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_subscribed', models.BooleanField(default=True)),
            ],
        ),
    ]
