# Generated by Django 5.0.4 on 2024-05-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks_tools', '0002_alter_user_tool_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
