# Generated by Django 5.0.4 on 2024-05-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks_tools', '0003_alter_hashtag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={'ordering': ['term']},
        ),
        migrations.RenameField(
            model_name='hashtag',
            old_name='name',
            new_name='term',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geeks_tools.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hashtag',
            name='subcategories',
            field=models.ManyToManyField(to='geeks_tools.subcategory'),
        ),
    ]
