# Generated by Django 5.0.4 on 2024-05-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks_tools', '0004_alter_category_options_alter_hashtag_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id', 'name']},
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='term',
            field=models.JSONField(),
        ),
    ]
