# Generated by Django 5.0.4 on 2024-05-20 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks_tools', '0005_alter_category_options_alter_hashtag_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='subcategories',
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='term',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='subcategories',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='geeks_tools.subcategory'),
            preserve_default=False,
        ),
    ]
