# Generated by Django 5.0.4 on 2024-05-21 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks_tools', '0006_remove_hashtag_subcategories_alter_hashtag_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_tool',
            name='logo',
        ),
        migrations.AddField(
            model_name='user_tool',
            name='subcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='geeks_tools.subcategory'),
            preserve_default=False,
        ),
    ]
