# Generated by Django 5.0.4 on 2024-05-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks_tools', '0008_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tool',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
